"use client"
import { ReactNode } from 'react'
import './globals.css'
import { SessionProvider } from "next-auth/react"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Iprops {
  children: ReactNode,
}

export default function RootLayout({ children }: Iprops) {
  return (
    <html lang="en">
      <body>

          {children}

      </body>
    </html>
  )
}
